# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fidSample <- function(VT2, VTsum, L, U) {
    .Call('_gfilmm_fidSample', PACKAGE = 'gfilmm', VT2, VTsum, L, U)
}

gfilmm_ <- function(L, U, FE, RE, RE2, E, N, thresh) {
    .Call('_gfilmm_gfilmm_', PACKAGE = 'gfilmm', L, U, FE, RE, RE2, E, N, thresh)
}

